### ISSUE TITLE
EVE Seat addon / PAPS are not working, need help

### ISSUE THREAD

**Issue by ghost** [BenHUET/eveseat-calendar#14]

**Comment by warlof** [comment]
Hello @Souldestry 

For the first part; did you pap any fleet into which the character you're on has been ?

For the second one; can you give me the error stack spawned in your logs just after showing this prompt ?

Used to be in `/var/www/seat/storage/logs/laravel-date.log`

**Comment by Souldestry** [comment]
Hey here are the logfiles:

[laravel-2018-05-31.log](https://github.com/BenHUET/eveseat-calendar/files/2064905/laravel-2018-05-31.log)
[laravel-2018-06-01.log](https://github.com/BenHUET/eveseat-calendar/files/2064906/laravel-2018-06-01.log)

**Comment by warlof** [comment]
Ok, so... PAP mecanic is tied to SeAT itself.
There is no link with aDashboard which is not providing API to collect data.

For the second, it seems you didn't run migration.
`php artisan vendor publish --all --force`
`php artisan migrate`

**Comment by Souldestry** [comment]
> Ok, so... PAP mecanic is tied to SeAT itself.
There is no link with aDashboard which is not providing API to collect data.

So but ADashboard use the same esicode:
![grafik](https://user-images.githubusercontent.com/39839942/40874444-9b89831a-666f-11e8-8ae6-0ffc4d0c4b20.png)

Seat should be display the PAPs or not? SEAT read it from the esi code "esi_read_fleet" or not?



> For the second, it seems you didn't run migration.
php artisan vendor publish --all --force
php artisan migrate

I have migrate it, so I have used your commands (Installation instructions).

**Comment by warlof** [comment]
Closing the issue since it has not been update for weeks.
Fill free to reopen it if you're still stuck.
