### ISSUE TITLE
Wrong fitting Posted / not able to use Fitting Site anymore

### ISSUE THREAD

**Issue by kaho88** [BenHUET/eveseat-calendar#15]
Hey,

i pasted a new fitting to the tool.
Now i typed a "a" next to the shipname.

I got an error and now i only get "Whoops, looks like something went wrong."

restart didnt help. Any thoughts? Or wipe the DB?

Greetings

**Comment by warlof** [comment]
Hello @kaho88,

I've no idea about what you're talking :/
It's only showing calendar to handle operation and providing a PAP mechanic.

**Comment by kaho88** [comment]
hey warlof... Sorry i'm just braindead -.-"

your tool is fine, works great and i love it! 

Sorry xD

**Comment by warlof** [comment]
hum, all right
closing it so :p
