### ISSUE TITLE
Several bug after the update of SeAT

### ISSUE THREAD

**Issue by H4Z4RD-H42** [BenHUET/eveseat-calendar#17]
* **Problem**: _Whats wrong?_
Some functions of Calendar no longer work on my SeAT. The last thing I did as administrator, is to update SeAT to version [3.0.0 (no beta)](https://github.com/eveseat/seat/releases/tag/3.0.0), for this reason I gave this title to the issue. Below the list of problems:

1. **Calendar -> Settings -> Tags -> New**: when I create a new tag, the color table is no longer visible and the preview is not updated in real time (image 1).
2. **Calendar -> Settings -> Tags -> List**: clicking on the trash icon, the page is reloaded but the tag is not deleted. Pressing the edit icon, the relative window opens but also here the preview of tag does not work and also the color table, besides there is the icon of the loading that runs to infinity (image 2).
3. **Calendar -> Operations -> Create a New Operation**: here, the auto-completition for the solar system and the fleet commander does not work. Moreover, most importantly, pressing the "Create this operation" button, nothing happens. In practice I can not create events anymore (image 3).

* **Expected**: _What did you expect to happen?_
That everything works as before.

* **Logs / Screenshots / Proof**: _The more information you give the better!_

**_image 1_**
![image](https://user-images.githubusercontent.com/6650832/41817423-4b556886-779b-11e8-9f86-8fda8f6a62a8.png)

_**image 2**_
![image](https://user-images.githubusercontent.com/6650832/41817456-bb72756e-779b-11e8-8a0f-7930cf376347.png)

_**image 3**_
![image](https://user-images.githubusercontent.com/6650832/41817478-1fb12aac-779c-11e8-8814-2514a61186cd.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
DigitalOcean Ubuntu 18.04 - SeAT Docker installation.

SeAT Api Installed: v3.0.0
SeAT Console Installed: v3.0.0
SeAT Eveapi Installed: v3.0.0
SeAT Notifications Installed: v3.0.0
SeAT Web Installed: v3.0.1
SeAT Services Installed: v3.0.0

Eve Online SDE Installed: sde-20180529-TRANQUILITY

**Comment by warlof** [comment]
Hey,

It seems you've an issue with assets publication.
Ensure you've publish them using `php artisan vendor:publish --force --all`.
(btw, remember to run migration scripts : `php artisan migrate`)

If issue still persists, can you provide me your browser information ?

**Comment by H4Z4RD-H42** [comment]
i'm sorry but today i make a mistake on my server and nothing work, after spend some hours to fix, i decide to reinstall seat from zero and i can't reproduce this issue, but at 99% you are right, i forgot to run vendor:publish and migrate. I thought that with the docker it was not necessary. Thank you.

**Comment by warlof** [comment]
Well, if you're issue is solved; you can close it indead ^^'
Happy that's working now :)
