### ISSUE TITLE
Papped members does not show up

### ISSUE THREAD

**Issue by zuiji** [BenHUET/eveseat-calendar#18]
papped members does not show up under Calender < papped fleet
dont know if its a bug or its a futer Request :D 

![udklip](https://user-images.githubusercontent.com/32148833/42403852-a167aafc-8184-11e8-91fa-bc4efd259517.PNG)

**Comment by warlof** [comment]
Hello
It's a feature request. Currently, there are no way to show papped character for a specific OP.

**Comment by warlof** [comment]
@zuiji adressed in 3.0.7
