### ISSUE TITLE
[Feature Request] Add RemindOperation to settings

### ISSUE THREAD

**Issue by jdrc** [BenHUET/eveseat-calendar#22]
Allow for the RemindOperation job to be set in Settings so that an admin can choose at what intervals reminders should be sent.

An example from my particular situation:
Currently we don't use the Slack integration at all as the Reminder pings are intrusive at the current 60,30,15 mins before kickoff. Ideally for us there would be no ping when an OP is set (or a post to Slack without a `@everyone` tag, then a single ping 5 minutes before the OP forms and that's it. Having this configurable would let us use the slack integration.

**Comment by H4Z4RD-H42** [comment]
Calendar really need this additions... Check also issue #16 and #20

**Comment by Dracks977** [comment]
for wait u can change timer in tabs on 
`/var/www/seat/vendor/kassie/calendar/src/Commands/RemindOperation.php`

**Comment by tigranm75** [comment]
Yep. Feature really needed. Too many people disabling notification due this.
