### ISSUE TITLE
Ping on edits Optional ?

### ISSUE THREAD

**Issue by flyingferret** [BenHUET/eveseat-calendar#23]
Love the app will hopefully help out my guys alot but the biggest push back I'm getting from my FC's is that they don't like the BoT Spam When Editing an OP.   Could this be made optional ?

**Comment by Crypta-Eve** [comment]
Confirming that this is would be amazing!!! Even just a checkbox for different things to ping on?

eg. Check boxes for:
 - Operation Posted
 - Operation Edited
 - Operation 1 hour away
 - Operation 30m away
 - Operation 15m away
 - Operation Starting

**Comment by Bluedagger21** [comment]
+1 for this.

Ideally, would like to enable certain post types and the type of mention to use (if any at all).

**Comment by alkari-verende** [comment]
This is addressed in #61
