### ISSUE TITLE
Reminder Ping Issues

### ISSUE THREAD

**Issue by Geabo** [BenHUET/eveseat-calendar#27]
I am getting two pings for every reminder event (1 hour, 30 mins, etc) and the link is broken. It points to "http://localhost/calendar/operation"

**Comment by warlof** [comment]
Hi @Geabo, if your address are wrong, it's because you didn't edit the public address of your `.env` file. You can find this into `APP_URL` variable.

Regarding pings, did you change anything from the default scheduled task?

**Comment by Geabo** [comment]
@warlof: always my savior. I did indeed forget to set `APP_URL`. Regarding the scheduled tasks, I never touch those.

Scheduled Tasks screen:
![Screenshot_1](https://user-images.githubusercontent.com/17442707/59621831-f0e51900-90e4-11e9-8fed-182df62a3ee1.png)

I only have one notification setup
![Screenshot_2](https://user-images.githubusercontent.com/17442707/59622075-7c5eaa00-90e5-11e9-956b-a509e0fc3a27.png)

And link that notification for the fleet
![Screenshot_3](https://user-images.githubusercontent.com/17442707/59622091-854f7b80-90e5-11e9-9a2c-1165d76ef055.png)

Additional info: It does not double the initial broadcast, only the reminders.

What did I do wrong?

**Comment by warlof** [comment]
@Geabo are you using a different timezone on either your server, PHP or SeAT itself than UTC ?

**Comment by akturis** [comment]
the same issue
timezone is everywhere UTC

**Comment by akturis** [comment]
> the same issue
> timezone is everywhere UTC
> http://bit.ly/2zYne1X

The problem was in crontab, twice job
# crontab -l -u www-data
* * * * * /usr/bin/php /var/www/seat/artisan schedule:run>> /dev/null 2>&1
* * * * * /usr/bin/php /var/www/seat/artisan schedule:run>> /dev/null 2>&1
