### ISSUE TITLE
Calendar Details not showing

### ISSUE THREAD

**Issue by mordrid** [BenHUET/eveseat-calendar#29]
When clicking on details the popup is blank.

In browser debug the request for OPTIONS is sent to the wrong URL https://16????.???/calendar/ajax/operation/0 when the site is hosted on https://0????.???/ . The number at the start of the URL is always the id of the calendar entry and /0 is always at the end.

**Comment by warlof** [comment]
Hi @mordrid,

Did you set the `APP_URL` from your `.env` file to the proper address?

**Comment by mordrid** [comment]
Hi,

The APP_URL is set to http instead of https, I can update this and try

**Comment by warlof** [comment]
That's definitely a good start.
`APP_URL` must reflect exactly the base public address you're using to reach SeAT.

**Comment by mordrid** [comment]
That didn't work, it broke everything, the docker image would not start correctly because it was expecting nginx to be listening on https, but our SSL is being added by a proxy outside.

**Comment by warlof** [comment]
Regarding the plugin itself, the operation ID is now resolved for instance published on IP address instead domain.
