### ISSUE TITLE
Have to run publish on every docker container restart?

### ISSUE THREAD

**Issue by porowns** [BenHUET/eveseat-calendar#32]
When running SEAT in docker, it seems like I have to run `php artisan vendor:publish --force` every time that the container is restarted?

Any way around this? Calendar isn't functional without it, but other packages work fine.

**Comment by warlof** [comment]
@porowns yeah, it's normal for both.

Calendar is using extra static css and javascript files which are moved from its directory to the public SeAT directory while you us `php artisan vendor:publish --force`.

Everytime you're using plugins, you're building a fresh new images.

The only tips I can give you is to persist the resulting image (once plugins has been added to the SeAT base image). That's an operation you'll have to do at every update. However, it will keep changes.

You'll find more information here https://docs.docker.com/engine/reference/commandline/commit/

**Comment by porowns** [comment]
Interesting, will open an issue on SEATs end.. for a clean user experience it should definitely publish extra static/css files from a community package on their Docker files.

**Comment by porowns** [comment]
https://github.com/eveseat/seat/issues/576
