### ISSUE TITLE
PAPs Recorded not working - Player "Unknown" / in "Unknown Corporation"

### ISSUE THREAD

**Issue by kaho88** [BenHUET/eveseat-calendar#47]
Hey,

PAPs work after the last Update (thx warlof). But the summary and record to the Chars dont work.
If you PAP a Fleet - they get registered in the Op with "Charname - Unknow"

Under the Summary Tab also the Player Name is "Unknow" and PAPs dont Count.

![image](https://user-images.githubusercontent.com/24758285/93591976-a15d5f00-f9b1-11ea-87ce-9f75dd5cc003.png)
![image](https://user-images.githubusercontent.com/24758285/93592866-3dd43100-f9b3-11ea-9da8-c1f49ab4610d.png)

**Comment by dougestey** [comment]
+1 on this. Also, interestingly, PAPs for characters not registered in Seat show the corp/alliance. It's only the ones in the system that do not show.

**Comment by akturis** [comment]
Need change function lookupConfirmed 
'character.affiliation:corporation_id' => 'character.affiliation'
```
   public function lookupConfirmed(Request $request)
    {
        $confirmed = Pap::with([
                'character:character_id,name',
                'character.affiliation',
                'user:id',
                'type:typeID,typeName,groupID',
                'type.group:groupID,groupName'
            ])

```
