### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by martinskalicky** [BenHUET/eveseat-calendar#54]
Using "Slack" integration and changing discord webhook URL with /slack at the end works.

However this intel is pretty hard to find.
Maybe it would be cool to mention it in documentation.

**Comment by Evolution0** [comment]
> Using "Slack" integration and changing discord webhook URL with /slack at the end works.
> 
> However this intel is pretty hard to find.
> Maybe it would be cool to mention it in documentation.

Could you elaborate on that. There does not seem to be an option in the calendar settings in SeAT to actually change the webhook URL which I find strange in and of itself, is this something that needs to be done by editing the plugins code somewhere?

**Comment by martinskalicky** [comment]
@Evolution0 That was actually what I was referring to. Was pretty hard to find that intel how its working.

**Comment by deMathias** [comment]
thanks guys i was looking for this!
